config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  resources :legislators, only: [:index]
  resources :users, only: [:update, :show]

  namespace :api do
    namespace :v1 do
      resources :legislators, only: [:index, :show]
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#create'

  get '/login' => redirect('/auth/facebook'), as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  get 'code', to: redirect('https://github.com/VikiAnn/funding_congress')
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  belongs_to :legislator
  validates :legislator, presence: true

  def self.cycle(legislator, year)
    if _database_contributors(legislator, year).empty?
      ContributorsFetcher.fetch(legislator, year)
    else
      _database_contributors(legislator, year)
    end
  end

  def self._database_contributors(legislator, year)
    where(legislator: legislator).where(cycle: year)
  end
end

app/models/legislator.rb
class Legislator < ActiveRecord::Base
  has_many :contributors

  def self.for_zipcode(zipcode)
    if _database_legislators(zipcode).empty?
      LegislatorsFetcher.fetch(zipcode)
    else
      _database_legislators(zipcode)
    end
  end

  def years_with_contributors
    Rails.cache.fetch("#{cache_key}_election_cycles") do
      election_cycles.select do |year|
        contributors.cycle(self, year).count > 0
      end
    end
  end

  def name
    "#{first_name} #{last_name}"
  end

  def full_name_and_title
    "#{title} #{name}, #{party}"
  end

  def photo_url
    "http://theunitedstates.io/images/congress/225x275/#{bioguide_id}.jpg"
  end

  def facebook_url
    "https://www.facebook.com/#{facebook_id}"
  end

  def twitter_url
    "https://twitter.com/#{twitter_id}"
  end

  def youtube_url
    "https://www.youtube.com/#{youtube_id}"
  end

  def campaign_contributors
    years_with_contributors
    contributors.map { |contributor| ContributorSerializer.new(contributor) }
    .group_by do |contributor|
      contributor.object.cycle
    end
  end

  def self._database_legislators(zipcode)
    where(zipcode: zipcode).where(in_office: true)
  end

  private

  def election_cycles
    (1990..Date.today.year).select {|year| year.even?}.map(&:to_s)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :zipcode, format: { with: /\A\d{5}\z/, message: "must be 5 digits" }, if: :zipcode?

  def update_from_omniauth(auth_data)
    send_welcome_email_if_new_user(auth_data)
    self.email      = auth_data["info"]["email"]
    self.name       = auth_data["info"]["name"]
    self.image_url  = auth_data["info"]["image"]
    self.token      = auth_data["credentials"]["token"]
    self.provider   = auth_data["provider"]
  end

  def send_welcome_email_if_new_user(auth_data)
    unless email && name
      UserWelcomeEmailJob.new.async.perform(user_name: auth_data["info"]["name"], email: auth_data["info"]["email"], uid: uid)
    end
  end
end

app/controllers/api/v1/legislators_controller.rb
class Api::V1::LegislatorsController < ApplicationController
  respond_to :json, :xml

  def index
    get_legislators
    @zipcode = params[:zipcode]
    respond_with @legislators
  end

  def show
    @legislator = Legislator.find(params[:id])
    respond_with @legislator
  end

  private

  def get_legislators
    if params[:zipcode]
      @legislators = Legislator.for_zipcode(params[:zipcode])
    else
      @legislators = Legislator.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController
  def index
    get_legislators
    @year = params[:cycle] || "2014"
    @zipcode = params[:zipcode]
    respond_to do |format|
      format.html
      format.json { render json: @legislators.to_json(include: :contributors) }
      format.xml { render xml: @legislators.to_xml(include: :contributors) }
    end
  end

  private

  def get_legislators
    if params[:zipcode]
      @legislators = Legislator.for_zipcode(params[:zipcode])
    elsif current_user && current_user.zipcode
      @legislators = Legislator.for_zipcode(current_user.zipcode)
    else
      @legislators = Legislator.all
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if facebook_login_was_successful?
      @user = User.find_or_create_by(uid: request.env["omniauth.auth"]["uid"])
      @user.update_from_omniauth(request.env["omniauth.auth"])
      @user.save!
      session[:user_id] = @user.id
      redirect_to legislators_path, notice: "Welcome, #{@user.name}!"
    else
      redirect_to root_path, notice: "Your Facebook login info was incorrect. Please try again."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You are now logged out"
  end

  private

  def facebook_login_was_successful?
    request.env["omniauth.auth"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user, :set_user

  def show
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to legislators_path
    else
      flash[:notice] = "A zipcode should be 5 digits"
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:zipcode, :email)
  end

  def require_current_user
    unless current_user.id == params["id"].to_i
      redirect_to root_path, notice: "You may only view your own information."
    end
  end

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/legislators_helper.rb
module LegislatorsHelper
  def active(cycle, current)
    if cycle == current
      "class=active"
    end
  end
end

app/views/contributors/_row.html.erb
<tr>
  <td><%= row.name %></td>
  <td><%= number_to_currency(row.employee_amount) %></td>
  <td><%= number_to_currency(row.direct_amount) %></td>
  <td><%= number_to_currency(row.total_amount) %></td>
</tr>

app/views/layouts/_flash.html.erb
<div class="alert-container text-center">
  <% if flash %>
    <% flash.each do |key, message| %>
    <div class="alert alert-info" role="alert">
      <%= message %>
    </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Funding Congress</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="account nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "My Legislators", legislators_path %></li>
          <li><%= link_to "Logout", logout_path, id: "logout" %></li>
          <li><a class="navbar-image" href="/users/<%= current_user.id %>"><img src="<%= current_user.image_url %>"  alt="facebook avatar" /></a></li>
        <% else %>
          <li><a id="login" href="/login">Login <i class="fa fa-facebook-square"></i></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FundingCongress</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'favi.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= render 'layouts/flash' %>
<%= yield %>

</body>
</html>

app/views/legislators/_legislator.html.erb
<div class="row legislators-block">
  <div class="row photo-and-contact-info">
    <div class="col-xs-2">
      <img src=<%= legislator.photo_url %> class="img-thumbnail img-rounded"  alt="legislator photo" />
    </div>
    <div class="col-xs-10 legislator-contact">
      <h3 class="legislator-name"><%= legislator.full_name_and_title %></h3>
      <div class="contact-text">
        <a href="<%= legislator.facebook_url %>"><i class="fa fa-facebook-square"></i></a>
        <a href="<%= legislator.twitter_url %>"><i class="fa fa-twitter-square"></i></a>
        <a href="<%= legislator.youtube_url %>"><i class="fa fa-youtube-square"></i></a> |
        <%= legislator.phone %> | <%= legislator.office %> | <a href="<%= legislator.website %>"><%= legislator.website %></a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <hr>
      <h4>Top Funding Contributors (by campaign cycle)</h4>
      <ul class="nav nav-tabs">
        <% legislator.years_with_contributors.each do |year| %>
          <li role="presentation" <%= active(year, selected_year) %>><%= link_to year, legislators_path(cycle: year, zipcode: zipcode, anchor: legislator.last_name) %></li>
        <% end %>
      </ul>

      <% if legislator.contributors.cycle(legislator, selected_year).present? %>
        <table class="table myTable tablesorter contributors_for_legislator_<%= legislator.id %>">
          <thead>
            <tr>
              <th>Organization</th>
              <th><span class="sortable">Individual &nbsp; <i class="fa fa-sort"></span></i></th>
              <th><span class="sortable">PAC &nbsp;<i class="fa fa-sort"></span></i></th>
              <th><span class="sortable">Total &nbsp;<i class="fa fa-sort"></i></span></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "contributors/row", collection: legislator.contributors.cycle(legislator.id, selected_year) %>
          </tbody>
        </table>
      <% else %>
        <br>
        Looks like this legislator wasn't in office in <%= selected_year %>!
        <br>
        <br>
      <% end %>
      SOURCE: <%= link_to "OpenSecrets.org", "https://www.opensecrets.org/politicians/" %> via the Sunlight Foundation's <%= link_to "Influence Explorer API", "http://sunlightlabs.github.io/datacommons/" %>
    </div>
  </div>
  <hr>
</div>

app/views/legislators/index.html.erb
<div class="container">
  <div class="row title-top">
    <div class="col-xs-12">
      <h1>My Legislators</h1>
    </div>
  </div>
  <% if !current_user || current_user.zipcode.present? %>
    <%= render @legislators, selected_year: @year, zipcode: @zipcode %>
  <% else %>
    <%= link_to "Add a zipcode to your profile so your legislators will appear here", user_path(current_user) %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container-full">

    <div class="row top-margin transparent">

      <div class="col-xs-12 text-center">
        <span class="giant-font">Who funds Congress?</span>
        <p class="lead">Find out who has been funding your representatives in Congress.</p>
      </div>

    </div> <!-- /row -->

    <div class="row">
      <div class="col-xs-12">
        <form action="/legislators" accept-charset="UTF-8" method="get">
          <div class="input-group">
            <input type="text" name="zipcode" class="form-control input-lg" placeholder="Enter your zipcode" title="Enter your zip to find your legislators">
            <span class="input-group-btn"><input type="submit" name="commit" value="go" class="btn btn-lg btn-primary"></span>
          </div>
        </form>
      </div>
    </div>

    <br><br><br><br><br><br>

    <div class="bottom-of-splash">
      <p>
        Photo by Bjoertvedt (own work) [<a href="http://creativecommons.org/licenses/by-sa/3.0">CC BY-SA 3.0</a> or <a href="http://www.gnu.org/copyleft/fdl.html">GFDL</a>], <a href="http://commons.wikimedia.org/wiki/File%3AUS_Congress_02.jpg">via Wikimedia Commons</a>
      </p>
    </div>

</div> <!-- /container full -->

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-4">
  </div>
  <div class="col-xs-4 text-center top-margin">
    <div>
      <h2><%= @user.name %></h2>
    </div>
    <div class="form-group">
      <%= form_for @user do |f| %>
        <%= f.label :zipcode, class: "sr-only" %>
        <%= f.text_field :zipcode, placeholder: "zipcode", class: "form-control" %>
        <%= f.label :email, class: "sr-only" %>
        <%= f.text_field :email, placeholder: "email", class: "form-control" %>
        <br>
        <%= f.submit "Update", class: "btn btn-default btn-lg" %>
      <% end %>
    </div>
  </div>
  <div class="col-xs-4">
  </div>
</div>